cask "ai-model-manager" do
  version "0.1.5"
  sha256 "72023c91adf167ff28d4f5a61bcb1c5b94b747f159ef363cec66246eb0990a1a"

  url "https://github.com/ziguifrido/ai-model-manager/releases/download/v#{version}/AIModelManager.zip"

  name "AI Model Manager"
  desc "Discover and manage local AI models from Ollama, LM Studio, Hugging Face, MLX, and vLLM"
  homepage "https://github.com/ziguifrido/ai-model-manager"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: :sonoma

  app "AIModelManager.app"

  zap trash: [
    "~/Library/Application Support/AI Model Manager",
    "~/Library/Caches/com.marcos.my-ai-models",
    "~/Library/Preferences/com.marcos.my-ai-models.plist",
  ]
end

# Template placeholders:
#   0.1.5 — Semantic version (e.g. 1.0.0). Set from the git tag.
#   72023c91adf167ff28d4f5a61bcb1c5b94b747f159ef363cec66246eb0990a1a  — SHA256 of the ZIP archive. Generated by generate_checksums.sh.
#
# See scripts/setup_homebrew_tap.sh for automated publishing.
