cask "ai-model-manager" do
  version "0.1.4"
  sha256 "03d100c686cd4b0e554ba60a12e8687f4c261f71418434e81bc40bfab9b011a8"

url "https://github.com/ziguifrido/my-ai-models/releases/download/v#{version}/AIModelManager.zip"

name "AI Model Manager"
desc "Discover and manage local AI models from Ollama, LM Studio, Hugging Face, MLX, and vLLM"
homepage "https://github.com/ziguifrido/my-ai-models"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :sonoma"

  app "AIModelManager.app"

  zap trash: [
    "~/Library/Application Support/AI Model Manager",
    "~/Library/Caches/com.marcos.my-ai-models",
    "~/Library/Preferences/com.marcos.my-ai-models.plist",
  ]
end

# Template placeholders:
#   0.1.4 — Semantic version (e.g. 1.0.0). Set from the git tag.
#   03d100c686cd4b0e554ba60a12e8687f4c261f71418434e81bc40bfab9b011a8  — SHA256 of the ZIP archive. Generated by generate_checksums.sh.
#
# See scripts/setup_homebrew_tap.sh for automated publishing.
